---

- name: "Lunarvim | Checking if it's already installed."
  ansible.builtin.command: which lvim
  register: lvim_check
  ignore_errors: yes
  failed_when: lvim_check.rc != 0

- block:
  - name: "Lunarvim | Downloading Lunarvim install script"
    ansible.builtin.get_url:
      url: "https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh"
      dest: /tmp/
      mode: "0644"
      force: true
    notify:
      - Cleanup lunarvim install script

  - name: "Lunarvim | Install Lunarvim"
    ansible.builtin.command: bash /tmp/install.sh --install-dependencies
  when: lvim_check.rc != 0

- name: "Lunarvim | Ensure lvim config directory exists"
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/lvim"
    state: directory
    mode: "0755"

- name: "Lunarvim | Copy my own config file"
  ansible.builtin.copy:
    src: "config.lua"
    dest: "{{ ansible_user_dir }}/.config/lvim"
    mode: "0644"
