---

- name: "Lunarvim | Install Lunarvim"
  ansible.builtin.command: |
    bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh) -y

- name: "Lunarvim | Ensure lvim config directory exists"
  ansible.builtin.file:
    dest: "{{ ansible_user_dir }}/.config/lvim"
    state: directory
    mode: "0755"

- name: "Lunarvim | Copy my own config file"
  ansible.builtin.copy:
    src: "config.lua"
    dest: "{{ ansible_user_dir }}/.config/lvim"
    mode: "0644"
