---
- name: "Zsh | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: zsh_distribution_config

- name: "Zsh | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: zsh_distribution_config.stat.exists

- name: "zsh | install powerlevel10k theme"
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    version: "v1.20.0"
    depth: 1

- name: "zsh | install zsh-syntax-highlighting plugin"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: "zsh | install zsh-autosuggestions plugin"
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: "Zsh | Install custom config files"
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/{{ item }}"
  loop:
    - p10k.zsh
    - alias.zsh

- name: "Zsh | Install config files"
  ansible.builtin.copy:
    src: files/zshrc
    dest: "{{ ansible_user_dir}}/.zshrc"

