---
- name: "Neovim | {{ ansible_distribution }} {{ ansible_distribution_major_version }} | EPEL Repo"
  ansible.builtin.dnf:
    name:
      - 
    state: present
  become: true

- name: "Neovim | {{ ansible_distribution }} | Install"
  ansible.builtin.apt:
    name: neovim
    state: present
  become: true
